"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.toPinYin = exports.truncate = exports.palindrome = exports.reverseStr = exports.sleep = exports.Rgb_Hex = exports.filType = exports.createRdm = exports.colorRdm = exports.curTimeFormat = void 0;
var index_1 = require("./tools/index");
Object.defineProperty(exports, "curTimeFormat", { enumerable: true, get: function () { return index_1.curTimeFormat; } });
Object.defineProperty(exports, "colorRdm", { enumerable: true, get: function () { return index_1.colorRdm; } });
Object.defineProperty(exports, "createRdm", { enumerable: true, get: function () { return index_1.createRdm; } });
Object.defineProperty(exports, "filType", { enumerable: true, get: function () { return index_1.filType; } });
Object.defineProperty(exports, "Rgb_Hex", { enumerable: true, get: function () { return index_1.Rgb_Hex; } });
Object.defineProperty(exports, "sleep", { enumerable: true, get: function () { return index_1.sleep; } });
Object.defineProperty(exports, "reverseStr", { enumerable: true, get: function () { return index_1.reverseStr; } });
Object.defineProperty(exports, "palindrome", { enumerable: true, get: function () { return index_1.palindrome; } });
Object.defineProperty(exports, "truncate", { enumerable: true, get: function () { return index_1.truncate; } });
Object.defineProperty(exports, "toPinYin", { enumerable: true, get: function () { return index_1.toPinYin; } });
